# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 11, 761, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.excellineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.excellineEdit.setObjectName("excellineEdit")
        self.horizontalLayout.addWidget(self.excellineEdit)
        self.excelBrowseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.excelBrowseButton.setObjectName("excelBrowseButton")
        self.horizontalLayout.addWidget(self.excelBrowseButton)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 761, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.imagelineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.imagelineEdit.setObjectName("imagelineEdit")
        self.horizontalLayout_2.addWidget(self.imagelineEdit)
        self.imageBrowseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.imageBrowseButton.setObjectName("imageBrowseButton")
        self.horizontalLayout_2.addWidget(self.imageBrowseButton)
        self.verticalLayout.addWidget(self.widget_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 761, 141))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 221, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget1 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4.addWidget(self.widget1)
        self.searchButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout_4.addWidget(self.searchButton)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.frame_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 221, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.exportSoldButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.exportSoldButton.setObjectName("exportSoldButton")
        self.verticalLayout_3.addWidget(self.exportSoldButton)
        self.exportUnsoldButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.exportUnsoldButton.setObjectName("exportUnsoldButton")
        self.verticalLayout_3.addWidget(self.exportUnsoldButton)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exportSoldButton.clicked.connect(MainWindow.eventExportSoldReport)
        self.exportUnsoldButton.clicked.connect(MainWindow.eventExportUnsoldReport)
        self.searchButton.clicked.connect(MainWindow.eventSearch)
        self.excelBrowseButton.clicked.connect(MainWindow.eventExcelBrowseData)
        self.imageBrowseButton.clicked.connect(MainWindow.eventImageBrowseData)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Report Helper"))
        self.label.setText(_translate("MainWindow", "Source Path"))
        self.excelBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Image Path"))
        self.imageBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.groupBox.setTitle(_translate("MainWindow", "Properties"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Export"))
        self.exportSoldButton.setText(_translate("MainWindow", "Export Sold Report"))
        self.exportUnsoldButton.setText(_translate("MainWindow", "Export unsold Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
